name: CI-CD

on:
  push:
    branches:
    - main
    - devel
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - main
    - devel
  workflow_dispatch:

env:
  ACTIONS_SETUP_PY3: '3.9'
  PY_COLORS: 1


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint using pre-commit hooks
    steps:
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.ACTIONS_SETUP_PY3 }}
      -
        name: Run pre-commit
        id: pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    name: Test code (Python ${{ matrix.py }} - ${{ matrix.os }})
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: [3.9]
    steps:
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v2
      -
        name: Set up Python ${{ matrix.py }}
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      -
        name: Set Python ${{ matrix.py }} cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
      -
        name : Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools tox tox-gh-actions coverage[toml]
      -
        name: Run tests via tox
        id: run-tox
        run: |
          python -m tox
      -
        name: Generate an XML report of coverage results
        id: cov-report-xml
        run: |
          python -m coverage xml
      -
        name: Upload coverage report to Codecov.io
        id: codecov-upload
        uses: codecov/codecov-action@v1
        with:
          name: "py${{ matrix.py }}-${{ matrix.os }}"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true


  publish-pypi:
    needs: [test]
    runs-on: ubuntu-latest
    name: Publish package to Python Packaging Index (PyPi)
    if: endsWith(github.ref, github.event.repository.default_branch) || ( github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') )
    steps:
      -
        name: Checkout
        id: checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.ACTIONS_SETUP_PY3 }}
      -
        name: Set Python ${{ env.ACTIONS_SETUP_PY3 }} cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
      -
        name : Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      -
        name: Build package
        id: build
        run: |
          python -m build -s -w .
      -
        name: Publish package to Test PyPI
        id: test-publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.SBRG_MACHINE_PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      -
        name: Publish package to PyPI
        id: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.SBRG_MACHINE_PYPI_TOKEN }}
